# Generated by Django 2.2.6 on 2019-11-26 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VideoGame',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_name', models.CharField(max_length=100)),
                ('genre', models.CharField(choices=[('RealTimeStrategy', 'RealTimeStrategy'), ('OnlineMassiveMultiplayerRPG', 'OnlineMassiveMultiplayerRPG'), ('ActionAdventure', 'ActionAdventure'), ('Sandbox', 'Sandbox'), ('Shooter', 'Shooter')], max_length=100)),
                ('rating', models.IntegerField()),
                ('platform', models.CharField(choices=[('Xbox', 'Xbox'), ('PS', 'PS'), ('PC', 'PC'), ('MobilePhone', 'MobilePhone'), ('NintendoSwitch', 'NintendoSwitch')], max_length=100)),
                ('release_date', models.DateTimeField(auto_now_add=True, help_text='Please use the following format: <em>YYYY-MM-DD</em>.')),
            ],
            options={
                'ordering': ['title_name'],
            },
        ),
    ]
