# Generated by Django 2.2.6 on 2019-11-26 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videogame',
            name='genre',
            field=models.CharField(choices=[('RTS', 'RealTimeStrategy'), ('MMORPG', 'OnlineMassiveMultiplayerRPG'), ('ACTION_ADVENTURE', 'ActionAdventure'), ('SANDBOX', 'Sandbox'), ('SHOOTER', 'Shooter')], max_length=100),
        ),
        migrations.AlterField(
            model_name='videogame',
            name='platform',
            field=models.CharField(choices=[('XBOX', 'Xbox'), ('PS', 'PS'), ('PC', 'PC'), ('MOBILE', 'MobilePhone'), ('SWITCH', 'NintendoSwitch')], max_length=100),
        ),
    ]
