# Generated by Django 2.2.6 on 2019-11-26 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_auto_20191126_1425'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videogame',
            name='genre',
            field=models.CharField(choices=[('RealTimeStrategy', 'RealTimeStrategy'), ('OnlineMassiveMultiplayerRPG', 'OnlineMassiveMultiplayerRPG'), ('ActionAdventure', 'ActionAdventure'), ('Sandbox', 'Sandbox'), ('Shooter', 'Shooter')], default='Sandbox', max_length=100),
        ),
        migrations.AlterField(
            model_name='videogame',
            name='platform',
            field=models.CharField(choices=[('Xbox', 'Xbox'), ('PS', 'PS'), ('PC', 'PC'), ('MobilePhone', 'MobilePhone'), ('NintendoSwitch', 'NintendoSwitch')], default='PC', max_length=100),
        ),
    ]
